package com.basinc.golfminus.exceptioncontrol;

import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.transaction.UserTransaction;

import org.jboss.seam.international.status.Messages;

/**
 * handler those exceptions generated by view expired management
 *
 * @author Scott
 */

//@HandlesExceptions
public class FileNotFoundExceptionHandler {
    @Inject private Messages messages;
    @Inject private FacesContext facesContext;
	@Inject	private UserTransaction utx;

    /**
     * Handles the exception thrown at the end of a conversation redirecting
     * the flow to a pretty page instead of printing a stacktrace on the screen.
     *
     * @param event
     * @param log
     * @throws IOException 
     */
//    public void fileNotFoundExceptionHandler(@Handles CaughtException<FileNotFoundException> event, Logger log) { 
//        	log.warn("fileNotFoundExceptionHandler: Page not found.");
//            try {
//                messages.info(new DefaultBundleKey("page_not_found")).defaults("The requested page does not exist.  Please start again.");
//                event.abort();
//                facesContext.getExternalContext().redirect("/error.xhtml");
//            } catch (IOException e) {
//                e.printStackTrace();
//            } catch (SecurityException e) {
//				e.printStackTrace();
//			} catch (IllegalStateException e) {
//				e.printStackTrace();
//			} catch (RollbackException e) {
//				e.printStackTrace();
//			} catch (HeuristicMixedException e) {
//				e.printStackTrace();
//			} catch (HeuristicRollbackException e) {
//				e.printStackTrace();
//			} catch (SystemException e) {
//				e.printStackTrace();
//			}
//	}
	
}
